### ISSUE TITLE
End-to-end test improvements

### ISSUE THREAD

**Issue by sedubois** [OpenCollective/api#289] opened 2016-04-19 14:10 UTC
Running circleci builds is quite long and should be sped up (approx. 20 min in API as of this writing), especially due to end-to-end tests.

Some ideas:
- parallelise nightwatch tests (maybe with https://circleci.com/docs/parallel-manual-setup/)
- check if caching of remotely-pulled repos really works
- investigate/speed up costly npm rebuild (triggered by `npm postinstall` in `website` and `app`)
- streamline tests (remove duplicates, avoid redundant database resets or other setups, etc)

**Comment by xdamman** [comment] 2016-04-28 12:13
Duplicate of https://github.com/OpenCollective/OpenCollective/issues/48

**Closed by xdamman** 2016-04-28 12:13 UTC
Labels: help wanted
